version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Root1234!
      - MYSQL_DATABASE=library_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - librarynetwork
    restart: always

  app:
    image: yukselmert/librarymanagement:latest
    container_name: librarymanagement
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/library_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Root1234!
    networks:
      - librarynetwork
    restart: always

networks:
  librarynetwork:
    driver: bridge
